services:
  postgres:
    build: .
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  etl:
    image: python:3.9
    container_name: python_etl
    depends_on:
      - postgres
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "pip3 install pandas psycopg2 && python etl_pg.py"

volumes:
  data: